version: "3"
services:
  webapp:
    build: .
    restart: always
    ports:
      - "8080:8080"
      - "80:80"
    expose:
      - 8080
      - 80
    environment:
      - LOGIN=admin
      - PASSWORD=admin
      - EMAIL=petyalom@yandex.ru
      - CONFIG_PATH=/home/anton/LoadBalancer/nginx.conf
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450